# Configurations
title:            霜月花繁录
longtitle:        霜月花繁录
author:           雪中明月
email:            lswlc33@qq.com
description: >
  霜月花繁录  BY  雪中明月

version:          1.0
gitbook_version:  3.2.3

url:              'wiki.xn--fiqz59cpva341l.ml'
baseurl:          'wiki.xn--fiqz59cpva341l.ml/'
rss:              RSS

toc:
  enabled: true
  h_min: 1
  h_max: 3

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jemoji
